### ISSUE TITLE
XNUCA2019Qualifier Web Ezphp非预期疑问

### ISSUE THREAD

**Issue by lxzmads** [NeSE-Team/OurChallenges#3]
根据wp看到此题非预期解1是通过如下配置
```
php_value pcre.backtrack_limit 0
php_value pcre.jit 0
```
导致preg_match返回False，从而绕过正则判断。

一番细究后发现原理应该是根据这篇[文章](https://www.leavesongs.com/PENETRATION/use-pcre-backtrack-limit-to-bypass-restrict.html)，文中的原理是利用超长字符串导致正则匹配的NFA引擎的回溯次数超过了默认配置100w导致`preg_match`返回false来进行bypass，这里设置`pcre.backtrack_limit 0`有异曲同工之妙。

但是本题的正则模式只是匹配单个字符串，理应是不存在回溯的。我本地复现时候时而可以成功，但是用崭新拉起容器来进行测试，却怎么也不行。很是奇怪。

想问下作者，这个非预期解具体是怎么亚子的。

**Comment by rebirthwyw** [comment]
https://xz.aliyun.com/t/6101#toc-2
你可以参考这篇wp来看看

**Comment by Mote-Z** [comment]
试下把环境删除干净之后重新build，我也碰到这个问题了，但是某次重新build之后就可以

**Comment by lxzmads** [comment]
找到了部分答案，
1. 根据这篇http://www.laruence.com/2010/06/08/1579.html是因为`match`函数的实现导致了回溯次数与直观的不一样，会多几次，所以设置`php_value pcre.backtrack_limit 0`才会work。

2. 复现时候还是时而不成功，具体原因还是不知道。
